config/routes.rb
Rails.application.routes.draw do

  get 'notifications/new'

  get 'notifications/create'

	devise_for :users, :controllers => { :registrations => "registrations" }
	resources :users do
		get 'ban'
		get 'unban'
	end

	resources :notifications
	resources :exchanges
	resources :reports
	resources :books do
		collection do
			get 'sell'
			post 'create_sell'
		end
		resources :listings do
			get 'buy'
			resources :offers
		end
 
	end

	match '/pages/terms' => "pages#terms", :via => [:get], :as => 'terms'
	match '/pages/library_exchange' => "pages#library_exchange", :via => [:get], :as => 'library_exchange'
	

	get 'library_inventory', to: 'exchanges#library_inventory'

	
	root 'application#landing'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
	validates :message, presence: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def new
  	@notification = Notification.new
  end

  def create
  	@notification = Notification.new notification_params
  	if @notification.save
  		redirect_to @notification, alert: "Notification created"
  	end
  end

  def show
  	@notification = Notification.find(params[:id])
  end

  def edit
  	@notification = Notification.find(params[:id])
  end

  def update
  	@notification = Notification.find(params[:id])
  	@notification.update(notification_params)
  	if @notification.save
  		redirect_to @notification, info: "Notification created"
  	end
  end

  def index
  	@notification = Notification.order("created_at").last
  	unless @notification.blank?	
  		redirect_to @notification
  	else
  		redirect_to url_for(:controller => :notifications, :action => :new)
  	end
  end

  private

  def notification_params
    params[:notification].permit(:message, :show)
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<div class="row col-md-10 col-md-offset-1">

<h2> Notification Form</h2>

<%= simple_form_for(@notification, html:{class:'form-horizontal'} ) do |f| %>
  
	
	
	
	<% if @notification.persisted? %>
		<%= f.input :show %>
	<% else %>
		<%= f.input :message %>
	<% end %>



	<div class='row text-center'>
	 <%= f.submit nil, class:'btn btn-primary' %>
	 <%= link_to 'Cancel', notifications_path, class:'btn btn-default' %>
	</div>

	<% end %>

</div>

app/views/notifications/create.html.erb
<h1>Notifications#create</h1>
<p>Find me in app/views/notifications/create.html.erb</p>

app/views/notifications/edit.html.erb
<%= render 'form' %>

app/views/notifications/new.html.erb
<%= render 'form' %>

app/views/notifications/show.html.erb
<div class="page-header">
	<h2>Notification Visible to Students</h2>
</div>

<div class="row">
	
	<h4> <%= @notification.message unless @notification.blank? %> </h4>
	<br>
	<%= link_to "Create a new notification", new_notification_path, class: 'btn btn-sm btn-info' %>
	<%= link_to "Show or hide this notification", edit_notification_path(@notification), class: 'btn btn-sm btn-info' %>

</div>