config/routes.rb
Rails.application.routes.draw do

  get 'notifications/new'

  get 'notifications/create'

	devise_for :users, :controllers => { :registrations => "registrations" }
	resources :users do
		get 'ban'
		get 'unban'
	end

	resources :notifications
	resources :exchanges
	resources :reports
	resources :books do
		collection do
			get 'sell'
			post 'create_sell'
		end
		resources :listings do
			get 'buy'
			resources :offers
		end
 
	end

	match '/pages/terms' => "pages#terms", :via => [:get], :as => 'terms'
	match '/pages/library_exchange' => "pages#library_exchange", :via => [:get], :as => 'library_exchange'
	

	get 'library_inventory', to: 'exchanges#library_inventory'

	
	root 'application#landing'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  first                  :string
#  last                   :string
#  banned                 :boolean
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#  roles_mask             :integer          default("0")
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :listings, dependent: :destroy
  has_many :offers, dependent: :destroy
  has_many :exchanges
  has_many :reports


  validates :first, presence:true
  validates :last, presence:true
  validates :email, presence:true, uniqueness:true
  validates_format_of :email, with: /andover\.edu/i, message: "must use andover.edu address"
  validates :first, presence: true
  validates :last, presence: true
  before_create :capitalize

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  ROLES = %w[superuser admin]
  
  def roles=(roles)
    # => %w[admin]
    self.roles_mask = (roles&ROLES).map{|r| 2**ROLES.index(r)}.inject(0,:+)
  end
  
  def roles
    ROLES.reject do |r|
      (roles_mask & 2**ROLES.index(r)).zero?
    end
  end
  
  def is?(role)
    # => true if matches a role for this user, false otherwise
    roles.include?(role.to_s)
  end

  def full_name
    self.first + " " + self.last
  end

  def capitalize
    self.first.capitalize!
    self.last.capitalize!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_filter :verify_admin_superuser, :only=>:index
  before_filter :verify_owner, :only=>:show

	def index
		@users = User.all.order(:last, :first)
	end

  def show
    @user = User.find(params[:id])
  end

  def ban
    @user = User.find(params[:user_id])
    @user.banned = true
    @user.save
    redirect_to users_path, alert: "User banned."
  end

  def unban
    @user = User.find(params[:user_id])
    @user.banned = false
    @user.save
    redirect_to users_path, notice: "User unbanned."
  end

  private

  def verify_admin_superuser
    # assume the route looks like this  /user/:username
    redirect_to books_path unless current_user.is?(:superuser) || current_user.is?(:admin)
  end  

  def verify_owner
    # assume the route looks like this  /user/:username
    redirect_to books_path unless current_user.is?(:superuser) || current_user.is?(:admin) || params[:id] == "#{current_user.id}"
  end  

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<tr>
	<td><%= link_to user.first, user %></td>
	<td><%= user.last %></td>
	<td><%= user.email %></td>
	<td>
	<% if (!user.banned?)%>
		<%= link_to "Ban", user_ban_path(user), class:"btn btn-xs btn-danger", data: { confirm: "You sure?" } %>
	<% else %>
		<%= link_to "Unban", user_unban_path(user), class:"btn btn-xs btn-success", data: { confirm: "You sure?" } %>
	<% end %>
	</td>
</tr>

app/views/users/index.html.erb
<div class="page-header">
	<h1>User Administration</h1>
</div>
<br>
<div class="row">
	<table class="table table-striped table-hover" id="users_table">
		<thead>
			<tr>
				<th>first</th>
				<th>last</th>
				<th>email</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			<%= render @users %>
		</tbody>
	</table>
</div>


<script>
$(document).ready(
	function() {
		$('#users_table').DataTable({
			paginationType: 'full_numbers'
		})
	}
	)
</script>

app/views/users/show.html.erb
<div class="page-header">
  <h1><%= show_name(@user) %></h1>
</div>

<div class="text-right">
	<%= link_to fa_icon('usd', text:'Sell A Book'), sell_books_path, class:'btn btn-lg btn-primary'%>
</div>
<div class="row">

	<h2>My Open Listings</h2>

	<table class='table table-hover'>
	    <thead>
		    <tr>
		      <th colspan="2"></th>
		    </tr>
		    <tr>
			  <th>Listing</th>
			  <th>Price</th>
		    </tr>
		</thead>
		<tbody>
			<% @user.listings.where(status:true).each do |listing| %>
			<tr>   
			<td><%= link_to listing.book.title, book_listing_path(listing.book, listing) %></td>
			<td><%= show_price(listing.min_price,2) %></td>				
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

<div class="row">
	<h2>Past Purchases</h2>
	<table class='table table-hover'>
	    <thead>
		    <tr>
		      <th colspan="6"></th>
		    </tr>
		    <tr>
			    <th> Exchange ID</th>
			    <th> Listing </th>
			    <th> Price </th>
			    <th> Buyer </th>
				<th> Seller </th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<%= render @user.exchanges.reverse %>
		</tbody>
	</table>
</div>

<div class="row">
	<h2>Past Sales</h2>
	<table class='table table-hover'>
	    <thead>
		    <tr>
		      <th colspan="6"></th>
		    </tr>
		    <tr>
			    <th> Exchange ID</th>
			    <th> Listing </th>
			    <th> Price </th>
			    <th> Buyer </th>
				<th> Seller </th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @user.listings.where(status:false).reverse.each do |listing| %>
				<% unless listing.exchange.nil? %>
					<%= render listing.exchange %>
				<% end %>
			<% end %>
		</tbody>
	</table>

</div>