config/routes.rb
Rails.application.routes.draw do

  get 'notifications/new'

  get 'notifications/create'

	devise_for :users, :controllers => { :registrations => "registrations" }
	resources :users do
		get 'ban'
		get 'unban'
	end

	resources :notifications
	resources :exchanges
	resources :reports
	resources :books do
		collection do
			get 'sell'
			post 'create_sell'
		end
		resources :listings do
			get 'buy'
			resources :offers
		end
 
	end

	match '/pages/terms' => "pages#terms", :via => [:get], :as => 'terms'
	match '/pages/library_exchange' => "pages#library_exchange", :via => [:get], :as => 'library_exchange'
	

	get 'library_inventory', to: 'exchanges#library_inventory'

	
	root 'application#landing'

end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <p class="text-muted credit">
    	<%= link_to "Andover Book Exchange", root_url %> designed by Ryan Brigden and Abhinav Venigalla.
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Andover Book Exchange</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60241847-1', 'auto');
  ga('send', 'pageview');

</script>

<div id="wrap">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <a class="navbar-brand" href= <%= root_url %>>Andover Book Exchange <%= show_role(current_user) %></a>
    </div>

    

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Welcome, #{current_user.first}", current_user %> </li>
          <li><a href= <%= books_path %> >Books</a></li>
        <% end %>

        <% if user_signed_in? && !(current_user.is?(:superuser) ||  current_user.is?(:admin))%>
          <li><a href="/pages/library_exchange" >OWHL Exchange</a></li>
        <% end %>
        
        <% if current_user && (current_user.is?(:superuser) ||  current_user.is?(:admin))%>
          <li><a href= <%= users_path %> >Users</a></li>
          <li><a href= <%= library_inventory_path %> >OWHL Inventory</a></li>
          <li><a href= <%= exchanges_path %> >Exchanges</a></li>
          <li><a href= <%= reports_path %> >Reports</a></li>
        <% end %>

        <li class ="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Options<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% if user_signed_in? %>
              <li><%= link_to 'My Page', current_user %></li>
              <li><%= link_to 'Terms of Service', terms_path %></li>
              <li><%= link_to 'Change Password', edit_user_registration_path %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, :method=>:delete %></li>
            <% else %>
              <li><%= link_to 'Log in', new_user_session_path %></li>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <li><%= link_to 'Terms of Service', terms_path %></li>
              <li><%= link_to 'Forgot Password', new_user_password_path %></li>
            <% end %>
            <% if user_signed_in? && (current_user.is?(:superuser) ||  current_user.is?(:admin)) %>
              <li><a href= <%= notifications_path %> >Notifications</a></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>	

<div class="container">
   
  <% if notice %>
    <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
    </div>
  <% end %>


  <% if alert %>
    <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
    </div>
  <% end %>

	<%= yield %>
  <br><br>
</div>

</div> <!-- end wrap -->

<%= render "/layouts/footer" %>


</body>
</html>